services:
  auth:
    build:
      context: auth-service/
    ports:
      - 8088:8088
    env_file:
      - auth-service/.env
    depends_on:
      - db
    environment:
      # Requires a tunnel open to the test environment Active Directory
      DELTA_LDAP_URL: "ldap://host.docker.internal:2389"
      DATABASE_URL: "jdbc:postgresql://db:5432/postgres"
      DELTA_MARKLOGIC_LDAP_AUTH_APP_SERVICE: "http://host.docker.internal:8030/"
    profiles:
      - app
  db:
    image: postgres:16.1
    ports:
      - 5438:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 1
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  # AWS OpenTelemetry collector for sending traces to AWS X-Ray
  # In hosted environments this runs as a sidecar in ECS
  telemetry:
    image: amazon/aws-otel-collector:latest
    command: [ "--config=/etc/otel-agent-config.yaml" ]
    env_file:
      # Should contain AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY, or equivalent session credentials
      # for a user with at least AWSXRayDaemonWriteAccess permissions
      - auth-service/.env
    environment:
      - AWS_REGION=eu-west-1
    volumes:
      - ./terraform/modules/fargate/adot-config.yml:/etc/otel-agent-config.yaml
    ports:
      - "4317:4317" # OTLP receiver
    profiles:
      - tracing

volumes:
  pgdata:
