name: "Terraform security validation workflow"

on: workflow_call

jobs:
  validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_REGION: "eu-west-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: tfsec
        run: docker run --rm -v "${GITHUB_WORKSPACE}:/src:ro" aquasec/tfsec:v1.28.14 --force-all-dirs /src/terraform
