name: "Terraform deploy"

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        description: Desired image tag to be deployed

jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency: terraform
    environment: test
    defaults:
      run:
        working-directory: terraform/test
    env:
      AWS_REGION: "eu-west-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::486283582667:role/github-actions-terraform-admin
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Apply ${{ inputs.image_tag }}
        run: |
          terraform apply -auto-approve -input=false \
          -var="image_tag=${{ inputs.image_tag }}"

      - name: Wait for deployment to complete
        run: aws ecs wait services-stable --services ecs-service-test --cluster delta-auth-service-cluster-test
