name: "Check Terraform"

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform_check.yml"
      - ".github/workflows/terraform_validate.yml"
      - ".github/workflows/terraform_security.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform_check.yml"
      - ".github/workflows/terraform_validate.yml"
      - ".github/workflows/terraform_security.yml"

jobs:
  terraform-check:
    name: Check Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "terraform/"
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Terraform
        # Exposes stdout, stderr and exitcode as outputs for any steps that run terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Check formatting of all Terraform files
        id: fmt
        run: terraform fmt -check -diff -recursive
        working-directory: ./

  terraform-validate-test:
    name: Validate Test Terraform
    uses: ./.github/workflows/terraform_validate.yml
    with:
      workdir: terraform/test

  terraform-validate-staging:
    name: Validate Staging Terraform
    uses: ./.github/workflows/terraform_validate.yml
    with:
      workdir: terraform/staging

  terraform-validate-prod:
    name: Validate Production Terraform
    uses: ./.github/workflows/terraform_validate.yml
    with:
      workdir: terraform/production

  terraform-security:
    name: Check Terraform Security
    uses: ./.github/workflows/terraform_security.yml
